version: '3'

vars:
  COLOR: '\033[1;33m'
  RESET: '\033[0m'

silent: true

tasks:
  build:
    cmds:
      - echo -e "{{.COLOR}}BUILD{{.RESET}}"
      - go build

  run:
    cmds:
      - echo -e "{{.COLOR}}RUN{{.RESET}}"
      - go run .

  clean:
    cmds:
      - echo -e "{{.COLOR}}CLEAN{{.RESET}}"
      - go clean

  fmt:
    cmds:
      - echo -e "{{.COLOR}}FMT{{.RESET}}"
      - go fmt ./...

  vet:
    cmds:
      - echo -e "{{.COLOR}}VET{{.RESET}}"
      - go vet ./...

  default:
    cmds:
      - task: build
